/**
 * Writes the curated Krita brushes (brush library 05).
 *
 *   bun run tooling/krita-presets.ts [--bundle path/to/bundle] [--survey]
 *
 * Reads every `.kpp` in Krita's default bundle at the pinned commit, runs the
 * ones `CURATION` names through `engine/brush/krita-preset.ts` — the same
 * translator the in-app import uses — applies each entry's hand tuning, and
 * writes the result to `engine/brush/krita-presets.json`, grouped into the
 * sets Krita's own tags put them in. `--survey` prints every paintbrush preset
 * with its tags and what translating it drops, which is what a curator picks
 * from.
 *
 * What was dropped from each shipped brush is written beside the curation, to
 * `tooling/krita-presets/REPORT.md`.
 */
import { readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs"
import { dirname, join, resolve } from "node:path"

import type { Brush } from "../engine/brush/brush"
import { readGbr, readGih } from "../engine/brush/gimp-resources"
import {
  kritaPresetSlug,
  type KritaTip,
  parseKritaPreset,
  readKpp,
  translateKritaPreset,
} from "../engine/brush/krita-preset"
import { BUILTIN_BRUSH_PREFIX } from "../engine/brush/presets"
import shipped from "../features/studio/lib/krita-textures.json"
import { bundleBytes, COMMIT, readPng, unzip } from "./krita-assets/bundle"
import { CURATION, SETS } from "./krita-presets/curation"

const ROOT = resolve(import.meta.dir, "..")
const OUTPUT = join(ROOT, "engine/brush/krita-presets.json")
const REPORT = join(ROOT, "tooling/krita-presets/REPORT.md")

/** Each preset's tags, from the bundle manifest. */
function readTags(files: string): Map<string, string[]> {
  const xml = readFileSync(join(files, "META-INF/manifest.xml"), "utf8")
  const tags = new Map<string, string[]>()
  for (const entry of xml.matchAll(
    /manifest:full-path="paintoppresets\/([^"]+)"[\s\S]*?<\/manifest:file-entry>/g
  ))
    tags.set(
      entry[1],
      [...entry[0].matchAll(/<manifest:tag>([^<]*)<\/manifest:tag>/g)].map(
        (tag) => tag[1]
      )
    )
  return tags
}

/** Every tip Velura ships, sized from its source file before shrinking. */
function readTips(files: string): Map<string, KritaTip> {
  const tips = new Map<string, KritaTip>()
  for (const texture of shipped.textures) {
    if (texture.kind !== "tip") continue
    const file = join(files, texture.source)
    const bytes = new Uint8Array(readFileSync(file))
    const image = file.endsWith(".gih")
      ? readGih(bytes).cells[0]
      : file.endsWith(".gbr")
        ? readGbr(bytes)
        : readPng(bytes)
    tips.set(texture.id, {
      width: image.width,
      height: image.height,
      ...("selection" in texture && texture.selection
        ? { selection: texture.selection }
        : {}),
    })
  }
  return tips
}

async function main(files: string) {
  const tags = readTags(files)
  const tips = readTips(files)
  const grains = new Set(
    shipped.textures.filter((t) => t.kind === "grain").map((t) => t.id)
  )
  const folder = join(files, "paintoppresets")
  const translate = async (file: string, id?: string) => {
    const preset = parseKritaPreset(
      await readKpp(new Uint8Array(readFileSync(join(folder, file))))
    )
    if (preset.engine !== "paintbrush") return undefined
    return translateKritaPreset(preset, {
      id,
      tip: (tip) => tips.get(tip),
      grain: (id) => grains.has(id),
    })
  }

  if (process.argv.includes("--survey")) {
    for (const file of readdirSync(folder).sort()) {
      const result = await translate(file)
      if (!result) continue
      const { brush, dropped } = result
      console.log(
        `${file} [${(tags.get(file) ?? []).join(", ")}] r=${brush.shape.radius} tip=${brush.shape.tipTextureId ?? "auto"} grain=${brush.grain?.textureId ?? "-"} dyn=${brush.dynamics.map((m) => `${m.source}>${m.target}`).join(",")}`
      )
      for (const line of dropped) console.log(`    - ${line}`)
    }
    return
  }

  const sets = new Map<string, Brush[]>(SETS.map((set) => [set, []]))
  const report: string[] = [
    "# Krita brushes: what translation dropped",
    "",
    `Generated by \`tooling/krita-presets.ts\` from Krita ${COMMIT}.`,
    "",
  ]
  for (const entry of CURATION) {
    const fileTags = tags.get(entry.file)
    if (!fileTags) throw new Error(`${entry.file} is not in the bundle.`)
    if (!fileTags.includes(entry.set))
      throw new Error(`${entry.file} is not tagged ${entry.set} in Krita.`)
    const slug = kritaPresetSlug(entry.file)
    const result = await translate(
      entry.file,
      `${BUILTIN_BRUSH_PREFIX}krita-${slug}`
    )
    if (!result) throw new Error(`${entry.file} is not a paintbrush preset.`)
    const brush = entry.tune ? entry.tune(result.brush) : result.brush
    if (entry.name) brush.name = entry.name
    sets.get(entry.set)!.push(brush)
    report.push(
      `- **${brush.name}** (\`${entry.file}\`): ${result.dropped.length ? result.dropped.join("; ") : "nothing"}${entry.tune ? " (hand-tuned)" : ""}`
    )
  }

  const data = {
    source: {
      name: "Krita 4 default resources",
      commit: COMMIT,
      licence: "CC0 1.0",
    },
    sets: [...sets].map(([name, brushes]) => ({ name, brushes })),
  }
  writeFileSync(OUTPUT, `${JSON.stringify(data, null, 2)}\n`)
  writeFileSync(REPORT, `${report.join("\n")}\n`)
  console.log(`${CURATION.length} brushes in ${sets.size} sets`)
}

const files = unzip(await bundleBytes())
try {
  await main(files)
} finally {
  rmSync(dirname(files), { recursive: true, force: true })
}
